// ============================================================
// FLIGHT TARGET - DATA FILE
// Updated automatically by Claude Code Scheduled Task
// ============================================================

const lastUpdated = {
    timestamp: "2026-03-29T08:00:00.000Z",
    source: "Claude Code Scheduled Task",
    version: "1.1.0"
};

const destinations = {
    // North America
    "KJFK": { name: "New York", coords: [40.6413, -73.7781], facts: ["העיר המאוכלסת ביותר בארה״ב עם 8.3 מיליון תושבים", "ביתה של בורסת וול סטריט ומרכז הפיננסים העולמי", "מעל 800 שפות מדוברות – הגיוון הלשוני הגבוה ביותר בעולם", "מרכז דיפלומטי עצום בזכות מטה האו״ם על גדות ההאדסון", "מרכז תרבות עולמי: ברודוויי, MoMA, מטרופוליטן"] },
    "KLAX": { name: "Los Angeles", coords: [33.9425, -118.4081], facts: ["בירת תעשיית הסרטים ובידור עולמית – Hollywood", "אוכלוסייה של 4 מיליון עם נוף מגוון תרבותית", "מרחוק ניתן לצפות בהרי סיירה נבאדה מכוסי שלג", "מרכז סטארטאפ בולט לצד עמק הסיליקון", "מארחת את אולימפיאדת הקיץ 2028"] },
    "KIAD": { name: "Washington DC", coords: [38.9531, -77.4565], facts: ["בירת ארצות הברית ומרכז השלטון הפדרלי", "הבניין הלבן, הקפיטול והפנטגון בה ממוקמים", "מרכז דיפלומטי ענק עם 170+ שגרירויות", "מוזיאוני הסמיתסוניאן הם הגדולים בעולם", "ממוצע ביקורי משלחות דיפלומטיות: 200+ בשנה"] },
    "KORD": { name: "Chicago", coords: [41.9742, -87.9073], facts: ["העיר השלישית בגודלה בארה״ב", "מרכז עסקי ופיננסי ענק של אמריקה התיכונה", "ידועה בארכיטקטורה מדהימה וגורדי שחקים", "מרכז אמנות ומוזיקה (ג'אז, בלוז)", "נמל O'Hare הוא בין 10 העמוסים בעולם"] },
    "KMIA": { name: "Miami", coords: [25.7959, -80.2870], facts: ["שער התיירות לאמריקה הלטינית", "מרכז פיננסי ובינלאומי דרום-מזרחי", "ידועה בחוף South Beach ובחיי לילה", "כ-70% מהאוכלוסייה דוברי ספרדית", "מרכז שיפינג ולוגיסטיקה בין-אמריקאי"] },
    "CYYZ": { name: "Toronto", coords: [43.6777, -79.6248], facts: ["העיר הגדולה ביותר בקנדה עם 6.2 מיליון תושבים", "גיוון תרבותי: 200+ לאומויות, 140 שפות", "מרכז פיננסי מוביל בצפון אמריקה", "ביתה של קהילה יהודית ענפה ופעילה", "מגדל CN Tower הוא אחד הגבוהים בעולם"] },

    // Western Europe
    "EGLL": { name: "London", coords: [51.4700, -0.4543], facts: ["הבירה הגדולה במערב אירופה עם 9 מיליון תושבים", "נמל התעופה הית'רו – מהעמוסים בעולם", "מרכז עולמי לתרבות, פיננסים, אקדמיה ודיפלומטיה", "הרכבת התחתית (הטיוב) היא העתיקה בעולם (1863)", "ביתם של 5 אתרי מורשת עולמית של אונסק״ו"] },
    "LFPG": { name: "Paris", coords: [49.0097, 2.5479], facts: ["'עיר האורות' – מרכז אופנה, אמנות וגסטרונומיה", "מוזיאון הלובר – המתויר בעולם עם 10 מיליון מבקרים", "יעד מועדף לתערוכות יוקרה ואירועי תרבות בינ״ל", "מגדל אייפל נבנה ב-1889 כמבנה זמני לתערוכה", "מטה אונסק״ו, OECD ועשרות ארגונים בינ״ל"] },
    "EDDB": { name: "Berlin", coords: [52.3667, 13.5033], facts: ["בירת הסטארט-אפים של אירופה – 'עמק הסיליקון' הגרמני", "פי 9 מגודלה של פריז אך פחות צפופה – 3.7 מיליון", "יותר מ-170 מוזיאונים וגלריות בעיר", "קיר ברלין נפל ב-1989 – סמל לסוף המלחמה הקרה", "אירועי תרבות ענק: ברלינאלה, IFA, תערוכות אמנות"] },
    "EDDM": { name: "Munich", coords: [48.3537, 11.7750], facts: ["בירת בוואריה ומרכז כלכלי דרום-גרמני", "מטה BMW, Siemens ו-Allianz", "אוקטוברפסט – פסטיבל הבירה הגדול בעולם (6 מיליון)", "FC Bayern Munich – קבוצת הכדורגל העשירה ביותר בגרמניה", "נמל התעופה MUC מדורג בין הטובים באירופה"] },
    "LIMC": { name: "Milan", coords: [45.6301, 8.7231], facts: ["הבירה הכלכלית האמיתית של איטליה", "מרכז עולמי מוביל לאופנה ועיצוב – Fashion Week", "Salone del Mobile – תערוכת הרהיטים הגדולה בעולם", "מרכז פיננסי עצום: Borsa Italiana", "ביתו של קתדרלת הדואומו – מרהיב הגותיים"] },
    "LIRF": { name: "Rome", coords: [41.8003, 12.2389], facts: ["'העיר הנצחית' – 2,800 שנות היסטוריה", "מטה הוותיקן – מדינה עצמאית עם 800 אזרחים", "יותר מ-900 כנסיות בתוך גבולות העיר", "מרכז קתולי עולמי – יעד עלייה לרגל ודיפלומטיה", "פורום הרומי, הקולוסיאום וקסטל סנט אנג'לו"] },
    "LSZH": { name: "Zurich", coords: [47.4582, 8.5555], facts: ["המרכז הפיננסי והבנקאי של שוויץ ואירופה", "מדורגת שנים רצופות כעיר באיכות חיים הגבוהה ביותר", "לא בירת שוויץ (ברן היא הבירה) – אך העיר הגדולה", "מעל 1,200 מזרקות בתוך העיר", "יעד פופולרי לתערוכות מסחר ועסקאות בינ״ל"] },
    "LSGG": { name: "Geneva", coords: [46.2370, 6.1089], facts: ["מרכז הדיפלומטיה הבינלאומית – מטה האו״ם האירופי", "ביתם של WHO, WTO, ICRC ועשרות ארגונים בינ״ל", "אגם ז'נבה ופסגות האלפים – יעד תיירות יוקרה", "מרכז שעונים ותכשיטים עולמי", "כנסי ויפורדות שלום היסטוריות התקיימו בה"] },
    "EBBR": { name: "Brussels", coords: [50.9010, 4.4844], facts: ["מושב המוסדות המרכזיים של האיחוד האירופי", "מטה ארגון נאט״ו ממוקם בה", "ידועה בוואפלים, שוקולד ובירה בלגית", "מרכז רב-לשוני של נוכחות בינלאומית אדירה", "כ-80,000 עובדי מוסדות אירופאיים מתגוררים בה"] },
    "LEMD": { name: "Madrid", coords: [40.4983, -3.5672], facts: ["הבירה הגדולה ביותר באיחוד האירופי (3.3 מיליון)", "ריאל מדריד – קבוצת הכדורגל המצליחה בעולם (15 גביעי Champions)", "מוזיאון הפראדו – אחד מבכירי מוזיאוני האמנות בעולם", "נמל התעופה שנקרא על שם אדולפו סואריס", "שוכנת בגובה 667 מטרים – הבירה הגבוהה ביותר באיחוד"] },
    "LEBL": { name: "Barcelona", coords: [41.2974, 2.0833], facts: ["בירת קטלוניה – ניב, תרבות ושאיפות עצמאות", "MWC – Mobile World Congress מתקיים כאן מדי שנה", "אנטוניו גאודי יצר את סאגרדה פמיליה ועוד אתרים", "FC Barcelona – האקדמיה La Masia מגדלת כשרונות עולמיים", "חוף ים, אדריכלות וחיי לילה – עיר קוסמופוליטית"] },
    "LOWW": { name: "Vienna", coords: [48.1103, 16.5697], facts: ["בירת המוזיקה הקלאסית – מוצרט, בטהובן, שוברט חיו כאן", "מטה IAEA, OPEC ו-UNODC", "גני שנברון – ארמון הבארוק המרהיב ומורשת עולמית", "בית הקפה הווינאי – מורשת תרבותית בלתי-מוחשית", "פילהרמונית וינה – אחת התזמורות היוקרתיות בעולם"] },
    "LGAV": { name: "Athens", coords: [37.9364, 23.9475], facts: ["עריסת הדמוקרטיה, הפילוסופיה והאולימפיאדה", "האקרופוליס ופרתנון – מורשת אנושות עצומה", "ראשונה לארח את האולימפיאדה המודרנית ב-1896", "בירת יוון עם 3.7 מיליון תושבים במטרופולין", "נמל פיראוס – הגדול ביותר בים התיכון"] },
    "EHAM": { name: "Amsterdam", coords: [52.3086, 4.7639], facts: ["בירת הולנד עם 165 תעלות רשומות כמורשת עולמית", "מרכז פיננסי מוביל – מטה Heineken, Shell, Philips", "מוזיאון ון גוך ובית אנה פרנק – יעדי תיירות עצומים", "הולנד מוסרת זכויות שנויות במחלוקת מחוץ לכללי EU", "נמל תעופה סכיפהול – הרביעי בגודלו באירופה"] },
    "EKCH": { name: "Copenhagen", coords: [55.6180, 12.6508], facts: ["בירת דנמרק – מדורגת בין ערי האושר ביותר בעולם", "מרכז עיצוב סקנדינבי מוביל", "ארמון אמליינבורג – מושב המשפחה המלכותית", "NOMA – מסעדה שקיבלה 3 כוכבי מישלן ו'מיטב בעולם'", "מרכז אנרגיה ירוקה וקיימות – 40% מהאנרגיה מרוח"] },
    "EPWA": { name: "Warsaw", coords: [52.1657, 20.9671], facts: ["נבנתה מחדש כמעט לחלוטין לאחר השמדתה ב-WWII", "המרכז הפיננסי הצומח ביותר במזרח אירופה", "ביתן של קהילות יהודיות עצומות לפני השואה (450,000)", "מוזיאון POLIN לתולדות יהודי פולין – פרס מוזיאון 2016", "יעד למשלחות מורשת יהודית ו'מצעד החיים'"] },
    "LHBP": { name: "Budapest", coords: [47.4298, 19.2611], facts: ["בירת הונגריה – 'פנינת הדנובה'", "גשרי שלשלת, פרלמנט ובתי מרחץ טורקיים", "מרכז יהודי היסטורי – בית הכנסת ברחוב דוהאני, הגדול באירופה", "פסטיבל SZIGET – אחד גדולי פסטיבלי המוזיקה באירופה", "2 מיליון תושבים; מרכז טכנולוגי צומח"] },
    "LKPR": { name: "Prague", coords: [50.1008, 14.2600], facts: ["'העיר המאה הזהבות' – שמורה בצורה יוצאת דופן", "טירת פראג – הטירה הגדולה בעולם מבחינת שטח", "מרכז תרבות אירופי מוביל ובית ספר לגיגית", "Franz Kafka נולד והתגורר בעיר", "אחת מהיעדים הפופולריים ביותר לתיירות באירופה"] },
    "ESSA": { name: "Stockholm", coords: [59.6519, 17.9186], facts: ["בירת שוודיה – פרושה על 14 איים", "טקס פרס נובל מוענק כאן בכל שנה ב-10 בדצמבר", "מרכז גיימינג ומוזיקה עולמי (Spotify, ABBA)", "אקדמיה השוודית – בוחרת זוכי נובל לספרות", "80% מהאנרגיה בשוודיה מקורות מתחדשים"] },

    // Middle East & Africa
    "OTHH": { name: "Doha", coords: [25.2731, 51.6081], facts: ["בירת קטאר – ארחה מונדיאל 2022", "חמאד אינטרנשיונל – נמל תעופה שנבחר לטוב בעולם 3 שנים רצוף", "הכלכלה מבוססת גז טבעי – GDP לנפש מהגבוהים בעולם", "ספינת הדגל Qatar Airways – אחת חברות התעופה הטובות", "Al-Jazeera – רשת חדשות בינ״ל ראשית ממוקמת בדוחה"] },
    "OMDB": { name: "Dubai", coords: [25.2532, 55.3657], facts: ["בורג' חליפה – הבניין הגבוה בעולם (828 מטר)", "מרכז עסקים ותיירות מוביל במזרח התיכון", "DXB – מהנמלים העמוסים ביותר בעולם בנוסעים בינ״ל", "EXPO 2020 Dubai – ביקר בו 24 מיליון מבקרים", "מרכז פיננסי DIFC – מרכז לפינטק ובנקאות"] },
    "FAOR": { name: "Johannesburg", coords: [-26.1392, 28.2460], facts: ["העיר הגדולה בדרום אפריקה ומרכזה הכלכלי", "ביתה של הבורסה הגדולה ביותר ביבשת אפריקה (JSE)", "Soweto – ביתו לשעבר של נלסון מנדלה", "מרכז כרייה עולמי – מרבית הזהב בעולם הופק כאן", "ארח מונדיאל FIFA 2010 – ראשון ביבשת אפריקה"] },
    "HKJK": { name: "Nairobi", coords: [-1.3192, 36.9275], facts: ["בירת קניה ומרכז מזרח אפריקה", "מטה UNEP ו-UN-Habitat – מטה או״ם בין הבודדים בעולם מתפתח", "פארק לאומי ה-Nairobi – חיות בר צמוד לעיר", "מרכז טכנולוגי הנקרא 'Silicon Savannah'", "פסטיבלי ספורט ענק – מרתון נאירובי ועוד"] },

    // Asia-Pacific
    "VHHH": { name: "Hong Kong", coords: [22.3080, 113.9185], facts: ["עיר פעלתנית – מרכז מסחר ופיננסים בין-אסייתי", "כלכלה חופשית מהבולטות בעולם – Gateway לסין", "שיאנית העולם במספר גורדי שחקים מעל 100 מטר", "מוזיאון ההיסטוריה של הונג קונג – 7,000 שנות תרבות", "נמל תעופה HKG – מהגדולים בנטל מטען בעולם"] },
    "RJTT": { name: "Tokyo", coords: [35.5494, 139.7798], facts: ["המטרופולין הגדול בעולם – 37 מיליון תושבים", "יותר כוכבי מישלן מכל עיר אחרת בעולם (230+)", "רשת רכבות ה-Shinkansen מהמדויקות ביותר בעולם", "מרכז חדשנות טכנולוגית, רובוטיקה ואנימה", "ארח אולימפיאדת 2021 (שנדחתה ממ-2020)"] },
    "RKSI": { name: "Seoul", coords: [37.4602, 126.4407], facts: ["ביתן של Samsung, LG, Hyundai, SK – ענקיות גלובליות", "הכי מהיר אינטרנט ציבורי בעולם – 5G בכל מקום", "Hallyu – גל הקוריאני: K-pop, K-drama, K-food", "DMZ – הגבול המבוצר ביותר בעולם 70 ק\"מ צפונה", "ינואר: CES Seoul ואירועי חדשנות בינ״ל רבים"] },
    "WSSS": { name: "Singapore", coords: [1.3644, 103.9915], facts: ["עיר-מדינה שהפכה למרכז פיננסי גלובלי תוך 50 שנה", "נמל הים העמוס ביותר בעולם בנפח סחר", "Gardens by the Bay – פנינת העיצוב הסביבתי", "Changi Airport – נבחר לנמל הטוב בעולם 12 פעמים", "מרכז ASEAN ופגישות גלובליות ענק (G20, APEC)"] },
    "ZBAA": { name: "Beijing", coords: [40.0801, 116.5846], facts: ["בירת סין – עיר עם 3,000 שנות היסטוריה", "הפורביידן סיטי – הארמון הגדול ביותר בעולם (180 בניינים)", "ארח אולימפיאדת 2008 ומשחקי חורף 2022 – עיר כפולה", "ציר הנסיעה המהיר HSR מחבר בייג'ינג לשנגחאי ב-4.5 שעות", "מטה החברה הסינית לחלל, אמנות ומשלחות ממשלתיות"] },
    "VABB": { name: "Mumbai", coords: [19.0896, 72.8656], facts: ["הבירה הכלכלית של הודו – GDP מטרופולין ענק", "Bollywood – תעשיית הסרטים הפוריה בעולם (1,000+ סרטים/שנה)", "ביתה של הבורסה BSE – העתיקה ביותר באסיה", "קהילה יהודית עתיקה: בני ישראל ויהודי עיראק", "מרכז לוגיסטיקה ושיפינג אסייתי מרכזי"] },

    // South America
    "SBGR": { name: "São Paulo", coords: [-23.4356, -46.4731], facts: ["העיר הגדולה ביותר בדרום אמריקה – 22 מיליון במטרופולין", "המרכז הכלכלי הגדול ביותר ביבשת אמריקה הלטינית", "קהילה יהודית מהגדולות בדרום אמריקה (130,000)", "מרכז פשיון – São Paulo Fashion Week", "Avenida Paulista – רחוב העסקים והפיננסים המרכזי"] },

    // Israel
    "LLBG": { name: "Tel Aviv / נתב\"ג", coords: [32.0055, 34.8854], facts: ["מרכז הסטארטאפ של ישראל – 'אומת הסטארטאפ'", "קרויה 'העיר ללא הפסקה' – חיי לילה ותרבות שוקקים", "עיר הבינלאומית הרשמית של ישראל", "מרכז 4X לשיחות, ועידות ודיפלומטיה יהודית-עולמית", "נמל תעופה Ben Gurion – שער ישראל לעולם"]},
    "LLHA": { name: "Haifa", coords: [32.8094, 35.0436], facts: ["עיר הנמל הגדולה של ישראל", "ביתם של כ-300 חברות היי-טק", "הר הכרמל ומרכז מחקר מוביל – הטכניון", "מרכז דתות: בהאי, נצרות, יהדות ואסלאם", "קהילת הדרוזים בנה שם קשרים בינלאומיים"] }
};

const flights = [
    // ============================================================
    // FOOTBALL - כדורגל
    // ============================================================
    {
        id: "F001",
        category: "football",
        title: "נבחרת ישראל – מוקדמות מונדיאל FIFA",
        mission: "Israel National Team – World Cup Qualifiers",
        background: "טיסת הנבחרת הלאומית למשחק מוקדמות גביע העולם. המשלחת כוללת 25 שחקנים, צוות אימון, רופא קבוצה, שני פיזיותרפיסטים, אנשי תקשורת ונציגי ה-IFA.",
        route: "LLBG -> LFPG",
        dest_icao: "LFPG",
        date: "2026-04-05",
        time: "10:30",
        airline: "El Al",
        aircraft: "Boeing 737-800",
        icon: "⚽",
        source: "Israeli Football Association",
        isNew: true
    },
    {
        id: "F002",
        category: "football",
        title: "מכבי תל אביב – UEFA Europa League",
        mission: "Maccabi Tel Aviv – Europa League Away Game",
        background: "משחק חוץ בשלב הבתים של הליגה האירופית. המועדון מטיס מטוס חכור עם 18 שחקנים, צוות ומאות אוהדים.",
        route: "LLBG -> EDDB",
        dest_icao: "EDDB",
        date: "2026-04-10",
        time: "14:15",
        airline: "Israir",
        aircraft: "Airbus A320neo",
        icon: "⚽",
        source: "Maccabi Tel Aviv FC Official Website"
    },
    {
        id: "F003",
        category: "football",
        title: "הפועל תל אביב – UEFA Europa Conference League",
        mission: "Hapoel Tel Aviv – Europa Conference League",
        background: "ההפועל מטוס לשלב הקבוצות של הליגת הקונפרנס. טיסה מסחרית שכורה עם הסגל המלא ומאות מאהדים.",
        route: "LLBG -> LGAV",
        dest_icao: "LGAV",
        date: "2026-04-18",
        time: "09:00",
        airline: "Aegean Airlines",
        aircraft: "Airbus A320",
        source: "Hapoel Tel Aviv FC Official Website",
        icon: "⚽"
    },
    {
        id: "F004",
        category: "football",
        title: "נבחרת ישראל – UEFA Nations League",
        mission: "Israel NT – UEFA Nations League Away Match",
        background: "משחק ליגת האומות בחוץ. הנבחרת עולה מדרגה אחרי עונה מרשימה. שחקני חוץ מגיעים ישירות מאירופה.",
        route: "LLBG -> EBBR",
        dest_icao: "EBBR",
        date: "2026-06-08",
        time: "11:45",
        airline: "Brussels Airlines",
        aircraft: "Airbus A319",
        source: "Israeli Football Association",
        icon: "⚽"
    },
    {
        id: "F005",
        category: "football",
        title: "מכבי חיפה – ליגת האלופות UEFA",
        mission: "Maccabi Haifa – UEFA Champions League Qualifier",
        background: "מכבי חיפה בדרך לשלב המוקדמות של ליגת האלופות. טיסת שכר מאורגנת עם כל הסגל.",
        route: "LLBG -> EDDM",
        dest_icao: "EDDM",
        date: "2026-07-22",
        time: "08:30",
        airline: "Lufthansa",
        aircraft: "Airbus A320",
        source: "Maccabi Haifa FC Official Website",
        icon: "⚽"
    },
    {
        id: "F006",
        category: "football",
        title: "נבחרת הנוער – UEFA U-21 Championship",
        mission: "Israel U-21 National Team – UEFA U-21 Championship",
        background: "נבחרת הנוער מטוסת לאליפות אירופה ב-U21. קבוצה מוכשרת עם פוטנציאל גדול לאחר עונה מצוינת.",
        route: "LLBG -> ESSA",
        dest_icao: "ESSA",
        date: "2026-06-14",
        time: "13:00",
        airline: "El Al",
        aircraft: "Boeing 737-900",
        source: "Israeli Football Association",
        icon: "⚽"
    },

    // ============================================================
    // BASKETBALL – כדורסל
    // ============================================================
    {
        id: "B001",
        category: "basketball",
        title: "מכבי תל אביב – EuroLeague",
        mission: "Maccabi Playtika Tel Aviv – EuroLeague",
        background: "טיסה רשמית למשחק יורוליג נגד ריאל מדריד. משחק קריטי למיקום בטבלה לקראת הפלייאוף. 12 שחקנים, צוות ו-50 אוהדים.",
        route: "LLBG -> LEMD",
        dest_icao: "LEMD",
        date: "2026-04-03",
        time: "09:00",
        airline: "El Al",
        aircraft: "Boeing 737-900",
        icon: "🏀",
        source: "Maccabi Tel Aviv Basketball Official Website"
    },
    {
        id: "B002",
        category: "basketball",
        title: "מכבי ת\"א כדורסל – EuroCup Basketball",
        mission: "Maccabi – EuroCup Away Quarter-Final",
        background: "ר.בע של היורוקאפ. משחק חוץ קריטי. הצוות יוצא בטיסת שכר מיוחדת עם אוהדים.",
        route: "LLBG -> LIMC",
        dest_icao: "LIMC",
        date: "2026-04-08",
        time: "10:20",
        airline: "Israir",
        aircraft: "Airbus A321neo",
        icon: "🏀",
        source: "Maccabi Tel Aviv Basketball Official Website"
    },
    {
        id: "B003",
        category: "basketball",
        title: "נבחרת ישראל כדורסל – FIBA EuroBasket",
        mission: "Israel Basketball National Team – EuroBasket",
        background: "נבחרת ישראל בגברים בדרך לאליפות אירופה ב-FIBA. גרוע פנייה גדולה עם הסגל המלא.",
        route: "LLBG -> LHBP",
        dest_icao: "LHBP",
        date: "2026-08-28",
        time: "07:30",
        airline: "Wizz Air",
        aircraft: "Airbus A321",
        icon: "🏀",
        source: "Israel Basketball Association"
    },
    {
        id: "B004",
        category: "basketball",
        title: "מכבי אשדוד – EuroCup",
        mission: "Maccabi Ashdod – EuroCup Basketball",
        background: "עלייה של מכבי אשדוד לשלב הקבוצות של היורוקאפ. טיסה ראשונה של הקבוצה לאירופה העונה.",
        route: "LLBG -> EHAM",
        dest_icao: "EHAM",
        date: "2026-10-15",
        time: "15:30",
        airline: "KLM",
        aircraft: "Boeing 737-800",
        icon: "🏀",
        source: "Israel Basketball Association",
        isNew: true
    },

    // ============================================================
    // SPORTS-OTHER – ספורט ענפים נוספים
    // ============================================================
    {
        id: "S001",
        category: "sports-other",
        title: "נבחרת ג'ודו – אליפות העולם",
        mission: "Israel Judo Team – World Judo Championships",
        background: "נבחרת הג'ודו של ישראל יוצאת להתחרות באליפות העולם. המשלחת כוללת מדליסטים אולימפיים ואלופי עולם. פוטנציאל גבוה למדליות זהב.",
        route: "LLBG -> RJTT",
        dest_icao: "RJTT",
        date: "2026-05-14",
        time: "22:30",
        airline: "El Al",
        aircraft: "Boeing 787-8 Dreamliner",
        source: "Israeli Judo Association",
        icon: "🥋"
    },
    {
        id: "S002",
        category: "sports-other",
        title: "נבחרת שחייה – World Aquatics Championships",
        mission: "Israel Swimming Team – World Aquatics Championships",
        background: "המשלחת הישראלית לאליפות העולם בשחייה. שחיינים ממים 50, 100 ו-200 מטר, לצד קפיצות מים ופולו מים.",
        route: "LLBG -> WSSS",
        dest_icao: "WSSS",
        date: "2026-07-14",
        time: "01:20",
        airline: "Singapore Airlines",
        aircraft: "Airbus A350-900",
        source: "Israeli Swimming Federation",
        icon: "🏊"
    },
    {
        id: "S003",
        category: "sports-other",
        title: "נבחרת אתלטיקה – World Athletics Championships",
        mission: "Israel Athletics Team – World Athletics Championships",
        background: "אתלטים ישראלים בדרך לאליפות העולם. ריצות ארוכות, שדה ופצצות ראוי לציון.",
        route: "LLBG -> EKCH",
        dest_icao: "EKCH",
        date: "2026-07-19",
        time: "06:15",
        airline: "SAS",
        aircraft: "Airbus A320neo",
        source: "Israeli Athletics Association",
        icon: "🏃"
    },
    {
        id: "S004",
        category: "sports-other",
        title: "נבחרת קראטה – World Karate Championships",
        mission: "Israel Karate National Team – World Championship",
        background: "נבחרת הקראטה הישראלית – אחת המובילות באירופה. שתי מדליות בעולם ב-5 שנים האחרונות.",
        route: "LLBG -> LIRF",
        dest_icao: "LIRF",
        date: "2026-10-05",
        time: "08:45",
        airline: "Alitalia / ITA Airways",
        aircraft: "Airbus A319",
        source: "Israeli Karate Association",
        icon: "🥊"
    },
    {
        id: "S005",
        category: "sports-other",
        title: "נבחרת סיוף – European Fencing Championships",
        mission: "Israel Fencing Team – European Championships",
        background: "אלופות ואלופים בסיוף יוצאים לאליפות אירופה. ישראל ידועה בבית ספר לסיוף איכותי.",
        route: "LLBG -> LKPR",
        dest_icao: "LKPR",
        date: "2026-06-20",
        time: "10:00",
        airline: "Czech Airlines",
        aircraft: "Airbus A319",
        source: "Israeli Fencing Association",
        icon: "🤺"
    },
    {
        id: "S006",
        category: "sports-other",
        title: "נבחרת טאקוונדו – Grand Prix Series",
        mission: "Israel Taekwondo – World Taekwondo Grand Prix",
        background: "ספורטאי הטאקוונדו הישראלים בדרך לסדרת הגרנד פרי. ציון דרך לקראת אולימפיאדה.",
        route: "LLBG -> RKSI",
        dest_icao: "RKSI",
        date: "2026-09-10",
        time: "20:45",
        airline: "Korean Air",
        aircraft: "Boeing 787-9",
        source: "Israeli Taekwondo Association",
        icon: "🦵"
    },
    {
        id: "S007",
        category: "sports-other",
        title: "נבחרת גלישה – ISA World Surfing Games",
        mission: "Israel Surfing Team – ISA World Surfing Games",
        background: "גולשים ישראלים מהמפורסמים בים התיכון יוצאים לאליפות העולם בגלישה. שמות גדולים בתחום.",
        route: "LLBG -> KLAX",
        dest_icao: "KLAX",
        date: "2026-09-01",
        time: "11:30",
        airline: "Delta",
        aircraft: "Boeing 767-300ER",
        source: "Israeli Surfing Association",
        icon: "🏄"
    },
    {
        id: "S008",
        category: "sports-other",
        title: "מרתון ברלין – צוות ישראלי",
        mission: "Israeli Athletes – Berlin Marathon",
        background: "קבוצת אצני מרתון ישראלים המתמודדים ב-Berlin Marathon, מהמהירים בעולם. שיאני ישראל כלולים.",
        route: "LLBG -> EDDB",
        dest_icao: "EDDB",
        date: "2026-09-27",
        time: "07:00",
        airline: "El Al",
        aircraft: "Boeing 737-800",
        source: "Israeli Athletics Association",
        icon: "🏅"
    },
    {
        id: "S009",
        category: "sports-other",
        title: "גביע דיוויס – נבחרת טניס",
        mission: "Israel Davis Cup Team – Davis Cup Finals",
        background: "נבחרת הטניס של ישראל בגביע דיוויס. המשלחת כוללת 5 שחקנים ומאמנים.",
        route: "LLBG -> LEMD",
        dest_icao: "LEMD",
        date: "2026-11-18",
        time: "09:30",
        airline: "Iberia",
        aircraft: "Airbus A320",
        source: "Israeli Tennis Association",
        icon: "🎾"
    },
    {
        id: "S010",
        category: "sports-other",
        title: "נבחרת גימנסטיקה – World Gymnastics Championship",
        mission: "Israel Gymnastics Team – World Artistic Gymnastics",
        background: "גימנסטים ישראלים מתמודדים בקטגוריות אמנות ואקרובטיקה. ישראל ידועה בגימנסטיקה קצבית.",
        route: "LLBG -> ZBAA",
        dest_icao: "ZBAA",
        date: "2026-10-18",
        time: "23:55",
        airline: "Air China",
        aircraft: "Boeing 777-300ER",
        source: "Israeli Gymnastics Federation",
        icon: "🤸"
    },
    {
        id: "S011",
        category: "sports-other",
        title: "נבחרת ירי – ISSF World Cup",
        mission: "Israel Shooting Sports – ISSF World Cup",
        background: "יורים ישראלים בדרך לגביע העולם של פדרציית הירי הבינ״ל. ספורט שישראל מצטיינת בו.",
        route: "LLBG -> LOWW",
        dest_icao: "LOWW",
        date: "2026-04-25",
        time: "10:00",
        airline: "Austrian Airlines",
        aircraft: "Airbus A320",
        source: "Israeli Shooting Federation",
        icon: "🎯"
    },

    // ============================================================
    // JEWISH MISSIONS – משלחות יהודיות
    // ============================================================
    {
        id: "J002",
        category: "jewish",
        title: "מצעד החיים – פולין",
        mission: "March of the Living – Auschwitz-Birkenau",
        background: "משלחת רשמית של 400 בני נוער, ניצולי שואה ונציגי ממשלה לימי הזיכרון בפולין. המשלחת כוללת שרים, נציגי צה״ל ורבנים.",
        route: "LLBG -> EPWA",
        dest_icao: "EPWA",
        date: "2026-04-20",
        time: "08:30",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        icon: "🕯️"
    },
    {
        id: "J003",
        category: "jewish",
        title: "משלחת JFNA – הפדרציות היהודיות",
        mission: "Jewish Federations of North America Mission",
        background: "200 מנהיגים ותורמים מ-JFNA בסיום ביקור הזדהות ותמיכה בישראל. לוגיסטיקה מורכבת של 4 קבוצות נפרדות.",
        route: "LLBG -> KJFK",
        dest_icao: "KJFK",
        date: "2026-06-05",
        time: "00:45",
        airline: "United",
        aircraft: "Boeing 787-10 Dreamliner",
        source: "Jewish Federations of North America",
        icon: "🤝"
    },
    {
        id: "J004",
        category: "jewish",
        title: "כנס רבנים בינלאומי – World Rabbinical Assembly",
        mission: "World Rabbinical Assembly – International Convention",
        background: "כנס עולמי של 500 רבנים מהמסורת הקונסרבטיבית והאורתודוקסית. 5 ימים של שיחות, הרצאות וסיורים.",
        route: "LLBG -> KJFK",
        dest_icao: "KJFK",
        date: "2026-06-20",
        time: "09:00",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        source: "World Rabbinical Assembly",
        icon: "📖"
    },
    {
        id: "J005",
        category: "jewish",
        title: "משלחת נוער יהודי – Jewish Youth Mission",
        mission: "International Jewish Youth Leadership Conference",
        background: "300 בני נוער מ-30 מדינות מגיעים לכנס מנהיגות יהודי בינ״ל בישראל. קבלת פנים ב-Ben Gurion.",
        route: "KJFK -> LLBG",
        dest_icao: "LLBG",
        date: "2026-07-10",
        time: "18:00",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        source: "Jewish Agency",
        icon: "🌟"
    },
    {
        id: "J006",
        category: "jewish",
        title: "אירועי יום הזיכרון – משלחות לפולין",
        mission: "Holocaust Remembrance Delegations – Yom HaShoah",
        background: "משלחות ממשלתיות ויהודיות ליום הזיכרון לשואה. כולל ביקורים ב-Auschwitz-Birkenau ואנדרטאות.",
        route: "LLBG -> EPWA",
        dest_icao: "EPWA",
        date: "2026-04-16",
        time: "10:00",
        airline: "LOT Polish Airlines",
        aircraft: "Boeing 787-8",
        source: "Yad Vashem",
        icon: "🕯️"
    },
    {
        id: "J007",
        category: "jewish",
        title: "אירוע יום העצמאות – שגרירות פריז",
        mission: "Yom Ha'atzmaut Celebration – Israeli Embassy Paris",
        background: "משלחת ממשלתית ותרבותית לאירוע הקהילה היהודית בפריז לרגל יום העצמאות. 78 שנה למדינה.",
        route: "LLBG -> LFPG",
        dest_icao: "LFPG",
        date: "2026-05-04",
        time: "12:00",
        airline: "Air France",
        aircraft: "Airbus A320",
        source: "Israeli Ministry of Foreign Affairs",
        icon: "🇮🇱"
    },
    {
        id: "J008",
        category: "jewish",
        title: "WZO – הסתדרות הציונית העולמית",
        mission: "World Zionist Organization – Annual Delegation",
        background: "הכינוס השנתי של ה-WZO בירושלים/תל אביב. משלחות מ-80 ארצות מגיעות ויוצאות לאורך שבוע.",
        route: "LLBG -> LSZH",
        dest_icao: "LSZH",
        date: "2026-06-30",
        time: "14:30",
        airline: "SWISS",
        aircraft: "Airbus A320neo",
        source: "World Zionist Organization",
        icon: "🌍"
    },
    {
        id: "J009",
        category: "jewish",
        title: "משלחת תורמים – מגבית ישראל",
        mission: "Israel Donor Mission – Major Jewish Philanthropists",
        background: "100 תורמים גדולים מארה״ב, קנדה ואירופה בסיום סיור תרומות בישראל. פגישות עם ראש הממשלה ושרים.",
        route: "LLBG -> KLAX",
        dest_icao: "KLAX",
        date: "2026-11-10",
        time: "12:00",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        source: "Jewish Agency",
        icon: "💛"
    },

    // ============================================================
    // DIPLOMATIC – דיפלומטיה וממשל
    // ============================================================
    {
        id: "G001",
        category: "diplomatic",
        title: "טיסת ראש הממשלה – עצרת האו״ם",
        mission: "PM Official Visit – UN General Assembly",
        background: "טיסה רשמית של ראש ממשלת ישראל לניו יורק לנאום בעצרת הכללית. המטוס: 'כנף ציון'. משלחת של 50 איש.",
        route: "LLBG -> KJFK",
        dest_icao: "KJFK",
        date: "2026-09-23",
        time: "11:00",
        airline: "Israeli Air Force",
        aircraft: "Boeing 767-300 (כנף ציון)",
        source: "Israeli Government",
        icon: "🏛️"
    },
    {
        id: "G002",
        category: "diplomatic",
        title: "משלחת משרד הביטחון – ועידת נאט״ו",
        mission: "Israeli MOD Delegation – NATO Defence Ministers Meeting",
        background: "שר הביטחון ומשלחת בכירה לוועידת שרי הביטחון של נאט״ו. ישראל שותפת קרובה לברית.",
        route: "LLBG -> EBBR",
        dest_icao: "EBBR",
        date: "2026-06-12",
        time: "07:30",
        airline: "Brussels Airlines",
        aircraft: "Airbus A330",
        source: "Israeli Ministry of Defense",
        icon: "🛡️"
    },
    {
        id: "G003",
        category: "diplomatic",
        title: "משלחת ישראל ל-OECD",
        mission: "Israeli Delegation – OECD Ministerial Council",
        background: "שר האוצר ובכירים ממשרד הכלכלה לדיונים מקצועיים בפריז. ישראל חברת ה-OECD מ-2010.",
        route: "LLBG -> LFPG",
        dest_icao: "LFPG",
        date: "2026-05-12",
        time: "08:15",
        airline: "El Al",
        aircraft: "Boeing 737-900ER",
        source: "Israeli Ministry of Finance",
        icon: "📈"
    },
    {
        id: "G004",
        category: "diplomatic",
        title: "ביקור שר החוץ – ברלין",
        mission: "Israeli FM State Visit – Germany",
        background: "ביקור מדינה של שר החוץ לגרמניה. פגישות עם עמיתים, קהילה יהודית ואירועי הנצחה.",
        route: "LLBG -> EDDB",
        dest_icao: "EDDB",
        date: "2026-04-28",
        time: "09:00",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        source: "Israeli Ministry of Foreign Affairs",
        icon: "🤝"
    },
    {
        id: "G005",
        category: "diplomatic",
        title: "משלחת ועידת האקלים – COP31",
        mission: "Israeli Delegation – COP31 Climate Conference",
        background: "נציגי ממשלה, סביבה ותעשייה בדרך לוועידת האקלים השנתית. ישראל מציגה יוזמות מים וחקלאות.",
        route: "LLBG -> WSSS",
        dest_icao: "WSSS",
        date: "2026-11-20",
        time: "22:00",
        airline: "Singapore Airlines",
        aircraft: "Airbus A350-900",
        source: "Israeli Ministry of Environmental Protection",
        icon: "🌱"
    },
    {
        id: "G006",
        category: "diplomatic",
        title: "משלחת ביטחונית – לונדון",
        mission: "Intelligence Cooperation Talks – London",
        background: "פגישות עבודה של בכירים במערכת הביטחון עם מקביליהם בבריטניה. שיתוף מידע וסייבר.",
        route: "LLBG -> EGLL",
        dest_icao: "EGLL",
        date: "2026-05-20",
        time: "06:45",
        airline: "British Airways",
        aircraft: "Boeing 787-9",
        source: "Israeli Ministry of Defense",
        icon: "🔐"
    },
    {
        id: "G007",
        category: "diplomatic",
        title: "ביקור נשיא המדינה – יוון",
        mission: "Israeli President State Visit – Greece",
        background: "ביקור מדינה רשמי של נשיא ישראל באתונה. חיזוק קשרי ישראל-יוון-קפריסין (EastMed).",
        route: "LLBG -> LGAV",
        dest_icao: "LGAV",
        date: "2026-05-05",
        time: "10:30",
        airline: "Israeli Air Force",
        aircraft: "Gulfstream G550",
        source: "Israeli Government",
        icon: "🏛️"
    },
    {
        id: "G009",
        category: "diplomatic",
        title: "משלחת סחר חוץ – טוקיו",
        mission: "Ministry of Economy Trade Mission – Japan",
        background: "משלחת עסקים ממשלתית ליפן. 40 חברות ישראליות בתחומי טכנולוגיה, אגרוטק ורפואה.",
        route: "LLBG -> RJTT",
        dest_icao: "RJTT",
        date: "2026-10-28",
        time: "22:00",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        source: "Israeli Ministry of Economy",
        icon: "✈️"
    },
    {
        id: "G010",
        category: "diplomatic",
        title: "חתימת הסכם שיתוף פעולה – ניו-דלהי",
        mission: "Bilateral Agreement Signing – Israel-India",
        background: "שר בכיר לחתימת הסכם שיתוף פעולה ישראל-הודו בחקלאות, מים וטכנולוגיה.",
        route: "LLBG -> VABB",
        dest_icao: "VABB",
        date: "2026-07-08",
        time: "01:30",
        airline: "Air India",
        aircraft: "Boeing 787-8",
        source: "Israeli Ministry of Foreign Affairs",
        icon: "📝"
    },

    // ============================================================
    // BUSINESS & TECH – עסקים וטכנולוגיה
    // ============================================================
    {
        id: "T003",
        category: "business",
        title: "Paris Air Show – Le Bourget",
        mission: "Israel Aerospace Delegation – Paris Air Show",
        background: "משלחות של תעשיות ביטחוניות ואזרחיות (IAI, Elbit, Rafael, Aeronautics) ל-Salon du Bourget.",
        route: "LLBG -> LFPG",
        dest_icao: "LFPG",
        date: "2026-06-16",
        time: "07:00",
        airline: "Air France",
        aircraft: "Airbus A350-900",
        source: "Israeli Aerospace Industries",
        icon: "✈️"
    },
    {
        id: "T004",
        category: "business",
        title: "Farnborough Airshow – בריטניה",
        mission: "Israeli Aerospace Industry – Farnborough International Airshow",
        background: "התעשייה האווירית הישראלית ב-Farnborough. עסקאות ביטחוניות ומסחריות בהיקף מיליארדי דולרים.",
        route: "LLBG -> EGLL",
        dest_icao: "EGLL",
        date: "2026-07-21",
        time: "08:00",
        airline: "British Airways",
        aircraft: "Airbus A320",
        source: "Israeli Aerospace Industries",
        icon: "🛩️"
    },
    {
        id: "T005",
        category: "business",
        title: "Eurosatory – תערוכת ביטחון פריז",
        mission: "Israeli Defense Industry – Eurosatory Paris",
        background: "התעשייה הביטחונית הישראלית ב-Eurosatory, התערוכה הצבאית-ביטחונית הגדולה בעולם.",
        route: "LLBG -> LFPG",
        dest_icao: "LFPG",
        date: "2026-06-15",
        time: "07:30",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        icon: "🛡️"
    },
    {
        id: "T006",
        category: "business",
        title: "CyberTech Tokyo – משלחת סייבר",
        mission: "Israeli CyberSec Delegation – CyberTech Tokyo",
        background: "20 חברות סייבר ישראליות ב-CyberTech Tokyo. ישראל מובילה עולמית בסייבר.",
        route: "LLBG -> RJTT",
        dest_icao: "RJTT",
        date: "2026-04-20",
        time: "23:00",
        airline: "El Al",
        aircraft: "Boeing 787-8 Dreamliner",
        source: "Israeli Chamber of Commerce",
        icon: "🔒"
    },
    {
        id: "T007",
        category: "business",
        title: "ArabianTravelMarket – דובאי",
        mission: "Israeli Tourism Delegation – Arabian Travel Market Dubai",
        background: "משרד התיירות ועסקי תיירות ישראלים בתערוכת ATM בדובאי. הסכמי שלום פתחו שוק חדש.",
        route: "LLBG -> OMDB",
        dest_icao: "OMDB",
        date: "2026-05-04",
        time: "08:00",
        airline: "El Al",
        aircraft: "Boeing 737-900",
        source: "Israeli Ministry of Tourism",
        icon: "🏨"
    },
    {
        id: "T008",
        category: "business",
        title: "MEDICA Düsseldorf – ציוד רפואי",
        mission: "Israeli MedTech Delegation – MEDICA Düsseldorf",
        background: "60 חברות ציוד רפואי ישראליות ב-MEDICA, התערוכה הרפואית הגדולה בעולם.",
        route: "LLBG -> EDDB",
        dest_icao: "EDDB",
        date: "2026-11-15",
        time: "09:00",
        airline: "Lufthansa",
        aircraft: "Airbus A319",
        source: "Israeli Chamber of Commerce",
        icon: "🏥"
    },
    {
        id: "T009",
        category: "business",
        title: "Agritech Berlin – חקלאות טכנולוגית",
        mission: "Israeli Agritech Companies – Berlin Agricultural Expo",
        background: "חברות חקלאות-טכנולוגיה ישראליות (Netafim, ICL, Naan Dan Jain) בתערוכה אירופית.",
        route: "LLBG -> EDDB",
        dest_icao: "EDDB",
        date: "2026-09-15",
        time: "11:00",
        airline: "El Al",
        aircraft: "Boeing 737-800",
        source: "Israeli Chamber of Commerce",
        icon: "🌾"
    },
    {
        id: "T010",
        category: "business",
        title: "GITEX Global Dubai – היי-טק",
        mission: "Israeli Tech at GITEX Global Dubai",
        background: "ביתן ישראל ב-GITEX, תערוכת הטכנולוגיה הגדולה במזרח התיכון. 50 חברות ומשקיעים.",
        route: "LLBG -> OMDB",
        dest_icao: "OMDB",
        date: "2026-10-12",
        time: "08:30",
        airline: "flydubai",
        aircraft: "Boeing 737 MAX 8",
        source: "Israeli Chamber of Commerce",
        icon: "🚀"
    },

    // ============================================================
    // CULTURE – תרבות ואומנות
    // ============================================================
    {
        id: "C002",
        category: "culture",
        title: "פסטיבל קאן – משלחת קולנוע ישראלי",
        mission: "Israeli Cinema Delegation – Cannes Film Festival",
        background: "במאים, שחקנים ומפיקים ישראלים ב-Cannes. ישראל ידועה בקולנוע פסטיבלים בינלאומי איכותי.",
        route: "LLBG -> LFPG",
        dest_icao: "LFPG",
        date: "2026-05-13",
        time: "09:30",
        airline: "Air France",
        aircraft: "Airbus A320",
        source: "Israeli Ministry of Culture",
        icon: "🎬"
    },
    {
        id: "C004",
        category: "culture",
        title: "פסטיבל ונציה – קולנוע ישראלי",
        mission: "Israeli Cinema – Venice International Film Festival",
        background: "פרויקטים ישראלים בסקציות שונות של פסטיבל ונציה. אחד הפסטיבלים הוותיקים בעולם.",
        route: "LLBG -> LIMC",
        dest_icao: "LIMC",
        date: "2026-08-26",
        time: "11:00",
        airline: "easyJet",
        aircraft: "Airbus A319",
        source: "Israeli Ministry of Culture",
        icon: "🦁"
    },
    {
        id: "C005",
        category: "culture",
        title: "שבוע האופנה – מילאנו",
        mission: "Israeli Fashion Designers – Milan Fashion Week",
        background: "מעצבי אופנה ישראלים מציגים ב-Milano Fashion Week. ישראל מפתחת תדמית אופנתית בינ״ל.",
        route: "LLBG -> LIMC",
        dest_icao: "LIMC",
        date: "2026-09-18",
        time: "08:45",
        airline: "Alitalia / ITA Airways",
        aircraft: "Airbus A319",
        source: "Israeli Ministry of Culture",
        icon: "👗"
    },
    {
        id: "C006",
        category: "culture",
        title: "ירידי הספרים – פרנקפורט",
        mission: "Israeli Publishers – Frankfurt Book Fair",
        background: "הוצאות ספרים, סופרים ומתרגמים ישראלים ב-Frankfurter Buchmesse, גדולה בעולם.",
        route: "LLBG -> EDDB",
        dest_icao: "EDDB",
        date: "2026-10-19",
        time: "07:30",
        airline: "Lufthansa",
        aircraft: "Airbus A320",
        source: "Israeli Ministry of Culture",
        icon: "📚"
    },
    {
        id: "C008",
        category: "culture",
        title: "להקת ענבל – פסטיבל ריקוד לונדון",
        mission: "Inbal Dance Theatre – London International Dance Festival",
        background: "להקת המחול הישראלית ענבל מציגה בלונדון. שילוב של מחול מזרחי ומודרני.",
        route: "LLBG -> EGLL",
        dest_icao: "EGLL",
        date: "2026-07-05",
        time: "10:30",
        airline: "El Al",
        aircraft: "Boeing 737-800",
        source: "Inbal Dance Theatre",
        icon: "💃"
    },
    {
        id: "C009",
        category: "culture",
        title: "תערוכת אמנות ישראלית – Amsterdam",
        mission: "Israeli Contemporary Art Exhibition – Amsterdam Stedelijk",
        background: "תערוכה נרחבת של אמנות עכשווית ישראלית במוזיאון Stedelijk. 30 אמנים, תערוכה מקיפה.",
        route: "LLBG -> EHAM",
        dest_icao: "EHAM",
        date: "2026-09-08",
        time: "08:00",
        airline: "KLM",
        aircraft: "Boeing 737-800",
        source: "Israeli Ministry of Culture",
        icon: "🎨"
    },
    {
        id: "AUTO-2026-05-12-001",
        category: "culture",
        title: "יורוויזיון – נציג ישראל בווינה",
        mission: "Israel Eurovision Song Contest Delegation – Vienna",
        background: "משלחת ישראל לתחרות יורוויזיון 2026 בווינה. הנציג הישראלי: נועם בתן עם השיר 'Michelle'. משלחת כוללת את הנציג, צוות ייצור, מנהלי הפרויקט ונציגי הטלוויזיה הישראלית.",
        route: "LLBG -> LOWW",
        dest_icao: "LOWW",
        date: "2026-05-12",
        time: "10:30",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        icon: "🎵",
        source: "Wikipedia / Eurovision Song Contest 2026"
    },
    {
        id: "AUTO-2026-04-07-001",
        category: "basketball",
        title: "מכבי ת\"א – יורוליג חוץ נגד בסקוניה",
        mission: "Maccabi Rapyd Tel Aviv – EuroLeague Away vs Baskonia Vitoria",
        background: "משחק חוץ רשמי של מכבי תל אביב בגמר עונת הסף של יורוליג נגד בסקוניה ויטוריה. הקבוצה טסה לביליבאו עם 12 שחקנים, צוות אימון ומאות אוהדים בטיסות מסחריות.",
        route: "LLBG -> LEBB",
        dest_icao: "LEBB",
        date: "2026-04-07",
        time: "08:00",
        airline: "Iberia",
        aircraft: "Airbus A320",
        icon: "🏀",
        source: "EuroLeague Basketball / Maccabi.co.il"
    },
    {
        id: "AUTO-2026-04-12-001",
        category: "jewish",
        title: "משלחת מצעד החיים – יציאה לפולין",
        mission: "March of the Living 2026 – Israeli Delegation Departure to Poland",
        background: "משלחת רשמית ישראלית של בני נוער, ניצולי שואה ונציגי מדינה יוצאת לפולין לקראת 'מצעד החיים' ביום השואה ה-14 באפריל 2026. המשלחת הולכת שלושה קילומטרים מאושוויץ לבירקנאו לזכר השואה.",
        route: "LLBG -> EPWA",
        dest_icao: "EPWA",
        date: "2026-04-12",
        time: "09:00",
        airline: "LOT Polish Airlines",
        aircraft: "Boeing 787-8 Dreamliner",
        icon: "🕯️",
        source: "EMOTL / March of the Living 2026"
    },
    {
        id: "AUTO-2026-06-15-001",
        category: "business",
        title: "Eurosatory 2026 – תעשיית הביטחון הישראלית",
        mission: "Israeli Defense Industry – Eurosatory 2026 Paris",
        background: "תעשיית הביטחון הישראלית (אלביט, תע\"א, רפאל) משתתפת ב-Eurosatory 2026, תערוכת הביטחון הגדולה ביותר בעולם. מתקיימת ב-15–19 ביוני 2026 ב-Parc des Expositions de Paris Nord Villepinte.",
        route: "LLBG -> LFPG",
        dest_icao: "LFPG",
        date: "2026-06-15",
        time: "06:30",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        icon: "🛡️",
        source: "Eurosatory.com"
    },
    {
        id: "AUTO-2026-04-15-001",
        category: "sports-other",
        title: "נבחרת ג'ודו – אליפות אירופה 2026 טביליסי",
        mission: "Israel Judo Team – European Judo Championships Tbilisi 2026",
        background: "נבחרת הג'ודו הישראלית יוצאת לאליפות אירופה 2026 בטביליסי, גאורגיה (16–19 באפריל). הנבחרת כוללת את רז הרשקו, אלופת עולם ב-+78 ק\"ג, וספורטאים נוספים. ישראל נחשבת לאחת המובילות בג'ודו האירופי ומייצגת מדי שנה בתחרויות היוקרתיות.",
        route: "LLBG -> UGTB",
        dest_icao: "UGTB",
        date: "2026-04-15",
        time: "08:00",
        airline: "Georgian Airways",
        aircraft: "Boeing 737-700",
        icon: "🥋",
        source: "International Judo Federation / IJF.org"
    },
    {
        id: "AUTO-2026-04-30-001",
        category: "sports-other",
        title: "נבחרת ג'ודו – גרנד סלאם דושנבה 2026",
        mission: "Israel Judo Team – IJF Grand Slam Dushanbe 2026",
        background: "ספורטאי ג'ודו ישראלים מתחרים בגרנד סלאם דושנבה, טג'יקיסטן (1–3 במאי 2026). אירוע מסלול עולמי של הפדרציה הבינ\"ל לג'ודו (IJF). ישראל שולחת ספורטאים לכל אירועי הגרנד סלאם כחלק מהכנה לאליפות העולם.",
        route: "LLBG -> UTDD",
        dest_icao: "UTDD",
        date: "2026-04-30",
        time: "06:00",
        airline: "לא ידוע",
        aircraft: "לא ידוע",
        icon: "🥋",
        source: "International Judo Federation / IJF.org"
    },
    {
        id: "AUTO-2026-06-17-001",
        category: "business",
        title: "VivaTech Paris 2026 – ביתן ישראל",
        mission: "Israeli Tech Startups – VivaTech Paris 2026",
        background: "ביתן ישראל ב-VivaTech 2026, אירוע הטכנולוגיה הגדול ביותר באירופה (17–20 ביוני, Paris Expo Porte de Versailles). ישראל משתתפת בתערוכה בפעם העשירית ברציפות. עשרות סטארטאפים וחברות טכנולוגיה ישראליות מציגות חדשנות בבינה מלאכותית, סייבר ובריאות דיגיטלית.",
        route: "LLBG -> LFPG",
        dest_icao: "LFPG",
        date: "2026-06-17",
        time: "07:30",
        airline: "Air France",
        aircraft: "Airbus A320neo",
        icon: "💡",
        source: "VivaTech Paris / Israeli Innovation Authority"
    },
    {
        id: "AUTO-2026-05-11-001",
        category: "culture",
        title: "משלחת ישראל – Eurovision Song Contest ווינה",
        mission: "Israeli Delegation – Eurovision Song Contest Vienna 2026",
        background: "משלחת רשמית של הערוץ השני בטלוויזיה הישראלית, מוסיקאים וצוות לתחרות השירה הבינלאומית בווינה. נוגם פולנבי בטן יחזיק דגל בתחרות. משלחת של 50 אנשים כוללת מהנדסי סאונד, מאפרים, עיצובנים וממנהלי פרויקט.",
        route: "LLBG -> LOWW",
        dest_icao: "LOWW",
        date: "2026-05-11",
        time: "10:00",
        airline: "El Al",
        aircraft: "Boeing 737-900",
        icon: "🎤",
        source: "Israeli Public Broadcasting Corporation"
    },
    {
        id: "AUTO-2026-05-12-002",
        category: "culture",
        title: "משלחת תרבות – פסטיבל קאן לקולנוע",
        mission: "Israeli Film Delegation – Cannes Film Festival 2026",
        background: "משלחת תרבות ישראלית ל-79 פסטיבל קאן הבינלאומי. 20 סרטים ישראליים ו-40 מייצגים מתעשיית הקולנוע הישראלית. דיוקנים בקטגוריות תחרות וקטגוריות מיוחדות.",
        route: "LLBG -> LFPG",
        dest_icao: "LFPG",
        date: "2026-05-12",
        time: "09:30",
        airline: "Air France",
        aircraft: "Airbus A320neo",
        icon: "🎬",
        source: "Israeli Ministry of Culture and Sports"
    },
    {
        id: "AUTO-2026-06-28-001",
        category: "jewish",
        title: "משלחות בינלאומיות – משחקי המכביה 2026",
        mission: "International Delegations Arrival – Maccabiah Games 2026",
        background: "קבלת משלחות בינלאומיות מ-55 מדינות לכ-8000 ספורטאים בתחרויות המכביה. משחקי הספורט היהודיים בפעם ה-22. משלחות מברית המועצות לשעבר, צפון אמריקה, דרום אמריקה, אירופה וחבר המדינות הקומונוולת.",
        route: "KJFK -> LLBG",
        dest_icao: "LLBG",
        date: "2026-06-28",
        time: "09:00",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        icon: "🥇",
        source: "Maccabiah Games Inc."
    },
    {
        id: "AUTO-2026-10-02-001",
        category: "sports-other",
        title: "נבחרת ג'ודו – World Judo Championships Baku",
        mission: "Israel Judo Team – World Judo Championships Azerbaijan",
        background: "נבחרת ישראל בג'ודו בדרך לאליפות העולם בבאקו, אזרבייג'ן (4–11 באוקטובר). המשלחת כוללת 30 ספורטאים, מאמנים, רופא קבוצה ופיזיותרפיסטים. ישראל שוגרת מדליסטים אולימפיים וזוכי תחרויות גדולות בינלאומיות.",
        route: "LLBG -> UUDD",
        dest_icao: "UUDD",
        date: "2026-10-02",
        time: "16:00",
        airline: "טורקיש אירלינס",
        aircraft: "Airbus A330-200",
        icon: "🥋",
        source: "Israeli Judo Association"
    },
    {
        id: "AUTO-2026-05-04-001",
        category: "jewish",
        title: "משלחת תגלית – Birthright Israel (Group B)",
        mission: "Birthright Israel Group Departure – May Group B",
        background: "קבוצת 50 משתתפים מצפון אמריקה וקנדה החוזרת לארה״ב לאחר סיור חינוכי של 10 ימים בישראל. המשתתפים בני גיל 18-32 מתגלית ישראל (Birthright).",
        route: "LLBG -> KJFK",
        dest_icao: "KJFK",
        date: "2026-05-04",
        time: "22:30",
        airline: "El Al",
        aircraft: "Boeing 787-9 Dreamliner",
        icon: "✡️",
        source: "Birthright Israel"
    },
    {
        id: "AUTO-2026-05-10-001",
        category: "jewish",
        title: "משלחת תגלית – Birthright Israel (Group C)",
        mission: "Birthright Israel Group Departure – May Group C",
        background: "קבוצת 45 משתתפים מדרום אמריקה וקנדה החוזרת לארה״ב לאחר סיור של 10 ימים בישראל. משתתפים בני גיל 18-32 מהתכנית החינוכית של תגלית ישראל.",
        route: "LLBG -> KLAX",
        dest_icao: "KLAX",
        date: "2026-05-10",
        time: "19:00",
        airline: "United",
        aircraft: "Boeing 787-10 Dreamliner",
        icon: "✡️",
        source: "Birthright Israel"
    },
    {
        id: "AUTO-2026-06-22-001",
        category: "jewish",
        title: "משלחת תגלית – Birthright Israel (Group D - Summer)",
        mission: "Birthright Israel Group Departure – June Summer Group",
        background: "קבוצת 55 משתתפים צעירים מצפון ודרום אמריקה החוזרת לארה״ב לאחר סיור קיץ אינטנסיבי של 10 ימים בישראל. משתתפים בני 18-32 מתוכנית התגלית השנתית.",
        route: "LLBG -> KORD",
        dest_icao: "KORD",
        date: "2026-06-22",
        time: "21:15",
        airline: "American Airlines",
        aircraft: "Boeing 777-200",
        icon: "✡️",
        source: "Birthright Israel"
    },
    {
        id: "AUTO-2026-11-23-001",
        category: "sports-other",
        title: "נבחרת טניס – Davis Cup Finals Bologna",
        mission: "Israel Tennis Team – Davis Cup Finals Italy",
        background: "נבחרת ישראל בטניס בדרך לגמר גביע דיויס בבולוניה, איטליה (24–29 בנובמבר). צוות של 5 שחקנים בדרגות עולמיות גבוהות עם מאמן וצוות רפואי. סיכוי גבוה למדליה של ישראל.",
        route: "LLBG -> LIPE",
        dest_icao: "LIPE",
        date: "2026-11-23",
        time: "08:30",
        airline: "Alitalia",
        aircraft: "Airbus A320",
        icon: "🎾",
        source: "Israeli Tennis Association"
    },
    {
        id: "AUTO-2026-04-09-001",
        category: "basketball",
        title: "מכבי ת\"א – יורוליג חוץ נגד פריז בסקטבול",
        mission: "Maccabi Rapyd Tel Aviv – EuroLeague Away vs Paris Basketball",
        background: "משחק חוץ רשמי של מכבי תל אביב ביורוליג נגד פריז בסקטבול (21:45 שעון מקומי). אחד ממשחקי הסיום של עונת הסף לפני שלב הפלי-אין. הקבוצה טסה לפריז עם 12 שחקנים וצוות אימון.",
        route: "LLBG -> LFPG",
        dest_icao: "LFPG",
        date: "2026-04-09",
        time: "09:30",
        airline: "El Al",
        aircraft: "Boeing 737-900",
        icon: "🏀",
        source: "EuroLeague Basketball / euroleaguebasketball.net"
    },
    {
        id: "AUTO-2026-09-24-001",
        category: "football",
        title: "נבחרת ישראל – ליגת האומות UEFA נגד אוסטריה",
        mission: "Israel NT – UEFA Nations League 2026/27 Away vs Austria",
        background: "ישראל נגד אוסטריה בשלב הקבוצות של ליגת האומות UEFA 2026/27 (ליגה B, קבוצה B3). ישראל בקבוצה עם אוסטריה, רפובליקת אירלנד וקוסובו. שלב הקבוצות מתקיים ספטמבר–נובמבר 2026. טיסת הנבחרת עם 25 שחקנים וצוות אימון.",
        route: "LLBG -> LOWW",
        dest_icao: "LOWW",
        date: "2026-09-24",
        time: "10:00",
        airline: "Austrian Airlines",
        aircraft: "Airbus A320",
        icon: "⚽",
        source: "UEFA / Israeli Football Association"
    },
    {
        id: "AUTO-2026-09-11-001",
        category: "sports-other",
        title: "נבחרת אתלטיקה – World Athletics Ultimate Championship בודפשט",
        mission: "Israeli Athletes – World Athletics Ultimate Championship Budapest 2026",
        background: "אתלטים ישראלים מתמודדים ב-World Athletics Ultimate Championship הראשון בהיסטוריה, שיתקיים בבודפשט, הונגריה (11–13 בספטמבר 2026). התחרות כוללת את המצטיינים ביותר בכל ענף מהסיזן – כ-48 הספורטאים הטובים בעולם בכל קטגוריה.",
        route: "LLBG -> LHBP",
        dest_icao: "LHBP",
        date: "2026-09-11",
        time: "07:30",
        airline: "Wizz Air",
        aircraft: "Airbus A321",
        icon: "🏃",
        source: "World Athletics / Israeli Athletics Association"
    },
    {
        id: "AUTO-2026-10-04-001",
        category: "football",
        title: "נבחרת ישראל – ליגת האומות נגד אירלנד (חוץ)",
        mission: "Israel NT – UEFA Nations League Away vs Republic of Ireland",
        background: "ישראל נגד אירלנד במשחק חוץ בליגת האומות UEFA 2026/27 (ליגה B, קבוצה B3). המשחק מתקיים ב-Aviva Stadium דבלין. ישראל בקבוצה עם אוסטריה, אירלנד וקוסובו. הנבחרת טסה עם 25 שחקנים וצוות אימון.",
        route: "LLBG -> EIDW",
        dest_icao: "EIDW",
        date: "2026-10-04",
        time: "10:00",
        airline: "El Al",
        aircraft: "Boeing 737-900",
        icon: "⚽",
        source: "UEFA / Israeli Football Association"
    },
    {
        id: "AUTO-2026-11-14-001",
        category: "football",
        title: "נבחרת ישראל – ליגת האומות נגד קוסובו (חוץ)",
        mission: "Israel NT – UEFA Nations League Away vs Kosovo",
        background: "ישראל נגד קוסובו במשחק חוץ בליגת האומות UEFA 2026/27 (ליגה B, קבוצה B3). משחק מחזור 5 שיתקיים בפרישטינה, קוסובו ב-14 בנובמבר 2026. הנבחרת טסה עם 25 שחקנים וצוות אימון.",
        route: "LLBG -> BKPR",
        dest_icao: "BKPR",
        date: "2026-11-14",
        time: "09:30",
        airline: "Wizz Air",
        aircraft: "Airbus A321",
        icon: "⚽",
        source: "UEFA / Israeli Football Association"
    }
];
